/**
 * CORE-10 - Learning Intelligence Foundation (Core Platform).
 *
 * buildIntelligenceReport() answers: what problem / where / since when /
 * which evidence / persistent? / prior intervention? / did it work? /
 * improving? / logical next action / confidence / enough evidence.
 *
 * Teacher Decision Boundary: NOT re-built. The canonical @workspace/decisions
 * capability is re-exported for downstream consumers and every proposal draft
 * is flagged requiresTeacherApproval=true. No insight ever delivers anything
 * autonomously (test-proven, plus the delivery gate itself lives in
 * @workspace/decisions and is enforced by core-08 tests).
 */
import { listEvidenceForStudent } from "@workspace/db";
import { buildLearnerModel } from "@workspace/db";
import type { LearnerModel } from "@workspace/db";
import { DEFAULT_INTELLIGENCE_CONFIG, type IntelligenceConfig, type IntelligenceReport, type ProposalDraft } from "./contracts.js";
import { evidenceDerivedHistory, type HistoryReader } from "./history.js";
import { buildInsights } from "./insights.js";

// Canonical teacher decision boundary REUSED, never duplicated.
export { applyTeacherDecision, issueDeliveryAuthorization, assertDeliveryAuthorized, assertActorCanDecide } from "@workspace/decisions";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface EvidenceRow {
  id: string;
  occurredAt: Date;
  sessionId: string | null;
  evidenceType: string;
  subject: string | null;
  response: unknown;
}

export type EvidenceReader = (q: { tenantId: string; studentId: string; limit?: number }) => Promise<EvidenceRow[]>;

export interface BuildReportArgs {
  tenantId: string;
  studentId: string;
  config?: Partial<IntelligenceConfig>;
  evidenceReader?: EvidenceReader;
  learnerBuilder?: (q: { tenantId: string; studentId: string }) => Promise<LearnerModel | null>;
  historyReader?: HistoryReader;
  now?: Date;
}

export async function buildIntelligenceReport(args: BuildReportArgs): Promise<IntelligenceReport> {
  const { tenantId, studentId } = args;
  if (!tenantId) throw new Error("TENANT_CONTEXT_MISSING");
  if (!studentId) throw new Error("STUDENT_CONTEXT_MISSING");
  if (!UUID_RE.test(tenantId)) throw new Error("INVALID_TENANT_ID");
  if (!UUID_RE.test(studentId)) throw new Error("INVALID_STUDENT_ID");
  const config: IntelligenceConfig = { ...DEFAULT_INTELLIGENCE_CONFIG, ...(args.config ?? {}) };
  const evidenceReader = args.evidenceReader as unknown as EvidenceReader;
  const reader = evidenceReader ?? (listEvidenceForStudent as unknown as EvidenceReader);
  const rows = await reader({ tenantId, studentId, limit: config.maxEvidenceRows });
  const learnerBuilder = args.learnerBuilder ?? buildLearnerModel;
  const learnerModel = await learnerBuilder({ tenantId, studentId }).catch(() => null);
  const historyReader = args.historyReader ?? evidenceDerivedHistory;
  const history = await historyReader({ tenantId, studentId, rows: rows as never });
  const insights = buildInsights({ tenantId, studentId, evidenceRows: rows, learnerModel, history, config, now: args.now });
  const source = insights.some((i) => i.source === "STATISTICAL") ? "STATISTICAL" : "RULE";
  return { tenantId, studentId, generatedAt: args.now ?? new Date(), source, insights };
}

export function proposalFromInsight(insight: {
  tenantId: string;
  studentId: string;
  dimension: { skill: string | null };
  evidenceRefs: string[];
  recommendation: { kind: ProposalDraft["kind"] } | null;
}): ProposalDraft {
  return {
    kind: insight.recommendation ? insight.recommendation.kind : "TEACHER_REVIEW",
    tenantId: insight.tenantId,
    studentId: insight.studentId,
    skill: insight.dimension.skill,
    rationale: "generated by learning intelligence for teacher review",
    evidenceRefs: insight.evidenceRefs,
    suggestedBy: "learning-intelligence",
    requiresTeacherApproval: true,
  };
}

export function assertTeacherApprovalRequired(draft: Pick<ProposalDraft, "requiresTeacherApproval">): void {
  if (draft.requiresTeacherApproval !== true) throw new Error("TEACHER_APPROVAL_REQUIRED");
}
