/**
 * GENERATED by lib/api-spec/generate-v1.mjs from lib/api-spec/v1.yaml — DO NOT EDIT.
 * Source of truth: the OpenAPI contract (CORE-24 Wave 3 governing principle).
 * Zod runtime validation mirrors (used by /v1 routers for body/query/params).
 */
import { z } from "zod";

export const ApiErrorSchema = z.object({
    "error": z.object({
      "code": z.string(),
      "message": z.string(),
      "requestId": z.string().optional(),
      "correlationId": z.string().optional(),
      "details": z.record(z.unknown()).optional()
    })
  });
export type ApiError = z.infer<typeof ApiErrorSchema>;

export const LoginRequestSchema = z.object({
    "email": z.string().email(),
    "password": z.string().min(1)
  });
export type LoginRequest = z.infer<typeof LoginRequestSchema>;

export const RefreshRequestSchema = z.object({
    "refreshToken": z.string().min(1)
  });
export type RefreshRequest = z.infer<typeof RefreshRequestSchema>;

export const LogoutRequestSchema = z.object({
    "refreshToken": z.string().optional()
  });
export type LogoutRequest = z.infer<typeof LogoutRequestSchema>;

export const StudentLoginRequestSchema = z.object({
    "identityId": z.string().uuid(),
    "claimed": z.object({
      "schoolId": z.string().uuid().optional(),
      "classId": z.string().uuid().optional(),
      "stageKey": z.string().optional(),
      "gradeLevel": z.string().optional()
    }).optional()
  });
export type StudentLoginRequest = z.infer<typeof StudentLoginRequestSchema>;

export const TokenPairResponseSchema = z.object({
    "user": z.object({
      "id": z.string(),
      "tenantId": z.string(),
      "role": z.string(),
      "email": z.string().optional(),
      "firstName": z.string().optional(),
      "lastName": z.string().optional()
    }),
    "accessToken": z.string(),
    "refreshToken": z.string()
  });
export type TokenPairResponse = z.infer<typeof TokenPairResponseSchema>;

export const StudentContextSchema = z.object({
    "studentId": z.string().uuid(),
    "classId": z.string().uuid(),
    "schoolId": z.string().uuid(),
    "organizationId": z.string().nullable().optional(),
    "stageKey": z.string().nullable().optional(),
    "gradeLevel": z.string()
  });
export type StudentContext = z.infer<typeof StudentContextSchema>;

export const MeResponseSchema = z.object({
    "user": z.object({
      "id": z.string(),
      "tenantId": z.string(),
      "role": z.string(),
      "email": z.string().optional(),
      "firstName": z.string().optional(),
      "lastName": z.string().optional()
    }),
    "studentContext": z.lazy(() => StudentContextSchema).optional()
  });
export type MeResponse = z.infer<typeof MeResponseSchema>;

export const StudentLoginResponseSchema = z.object({
    "context": z.lazy(() => StudentContextSchema),
    "accessToken": z.string(),
    "refreshToken": z.string()
  });
export type StudentLoginResponse = z.infer<typeof StudentLoginResponseSchema>;

export const PaginationMetaSchema = z.object({
    "total": z.number().int().min(0),
    "limit": z.number().int().min(1).max(200),
    "offset": z.number().int().min(0)
  });
export type PaginationMeta = z.infer<typeof PaginationMetaSchema>;

export const CurriculumAnchorSchema = z.object({
    "curriculumId": z.string(),
    "curriculumVersion": z.string(),
    "country": z.string().optional(),
    "educationSystem": z.string().optional(),
    "stageKey": z.string(),
    "gradeKey": z.string().optional(),
    "gradeLevel": z.string(),
    "subject": z.string(),
    "bookId": z.string().optional(),
    "unitId": z.string().optional(),
    "lessonId": z.string().optional(),
    "objectiveId": z.string().optional(),
    "skill": z.string().optional(),
    "dimension": z.string().optional()
  });
export type CurriculumAnchor = z.infer<typeof CurriculumAnchorSchema>;

export const ContentCreateRequestSchema = z.object({
    "title": z.string().min(1).max(300),
    "kind": z.string().min(1),
    "source": z.enum(["TEACHER_CREATED", "CURRICULUM", "SYSTEM", "REASSESSMENT", "REINFORCEMENT"]),
    "bodyRef": z.string().max(500).optional(),
    "language": z.string().optional(),
    "curriculum": z.lazy(() => CurriculumAnchorSchema),
    "metadata": z.record(z.unknown()).optional()
  });
export type ContentCreateRequest = z.infer<typeof ContentCreateRequestSchema>;

export const ContentResponseSchema = z.object({
    "id": z.string().uuid(),
    "tenantId": z.string().uuid(),
    "rootContentId": z.string().uuid().optional(),
    "parentVersionId": z.string().nullable().optional(),
    "version": z.number().int().min(1),
    "status": z.enum(["DRAFT", "PUBLISHED", "SUPERSEDED"]),
    "title": z.string(),
    "kind": z.string(),
    "source": z.string(),
    "bodyRef": z.string().nullable().optional(),
    "language": z.string().optional(),
    "curriculum": z.lazy(() => CurriculumAnchorSchema),
    "createdBy": z.string().optional(),
    "createdAt": z.string().optional(),
    "updatedAt": z.string().optional(),
    "metadata": z.record(z.unknown()).nullable().optional()
  });
export type ContentResponse = z.infer<typeof ContentResponseSchema>;

export const ContentMutationResponseSchema = z.object({
    "content": z.lazy(() => ContentResponseSchema),
    "created": z.boolean()
  });
export type ContentMutationResponse = z.infer<typeof ContentMutationResponseSchema>;

export const ContentListResponseSchema = z.object({
    "total": z.number().int(),
    "limit": z.number().int(),
    "offset": z.number().int(),
    "items": z.array(z.lazy(() => ContentResponseSchema))
  });
export type ContentListResponse = z.infer<typeof ContentListResponseSchema>;

export const ContentVersionsResponseSchema = z.object({
    "items": z.array(z.lazy(() => ContentResponseSchema))
  });
export type ContentVersionsResponse = z.infer<typeof ContentVersionsResponseSchema>;

export const ContentSupersedeRequestSchema = z.object({
    "title": z.string().min(1).max(300).optional(),
    "bodyRef": z.string().max(500).optional(),
    "kind": z.string().optional(),
    "metadata": z.record(z.unknown()).optional()
  });
export type ContentSupersedeRequest = z.infer<typeof ContentSupersedeRequestSchema>;

export const ExerciseCreateRequestSchema = z.object({
    "activityType": z.string().min(1),
    "engineBinding": z.enum(["READING", "DICTATION", "NUMERACY", "ASSESSMENT"]),
    "expectedResponseType": z.enum(["TYPED", "VOICE", "HANDWRITTEN", "SELECTION", "STEPS"]),
    "expectedResponseConfig": z.record(z.unknown()).optional(),
    "contentId": z.string().uuid().optional(),
    "assessmentRef": z.string().optional(),
    "maxAttempts": z.number().int().min(1).optional(),
    "timeLimitMs": z.number().int().min(1).optional(),
    "source": z.enum(["TEACHER_CREATED", "CURRICULUM", "SYSTEM", "REASSESSMENT", "REINFORCEMENT"]),
    "curriculum": z.lazy(() => CurriculumAnchorSchema),
    "metadata": z.record(z.unknown()).optional()
  });
export type ExerciseCreateRequest = z.infer<typeof ExerciseCreateRequestSchema>;

export const ExerciseResponseSchema = z.object({
    "exerciseId": z.string().uuid(),
    "tenantId": z.string().uuid(),
    "engineBinding": z.enum(["READING", "DICTATION", "NUMERACY", "ASSESSMENT"]),
    "contentRefs": z.array(z.string()).optional(),
    "expectedResponse": z.object({
      "type": z.enum(["TYPED", "VOICE", "HANDWRITTEN", "SELECTION", "STEPS"]),
      "maxAttempts": z.number().int().optional(),
      "timeLimitMs": z.number().int().optional()
    }),
    "curriculum": z.lazy(() => CurriculumAnchorSchema),
    "assessmentPolicyRef": z.string().optional(),
    "status": z.enum(["DRAFT", "PUBLISHED", "SUPERSEDED"]),
    "version": z.number().int(),
    "metadata": z.record(z.unknown()).nullable().optional()
  });
export type ExerciseResponse = z.infer<typeof ExerciseResponseSchema>;

export const ExerciseMutationResponseSchema = z.object({
    "exercise": z.lazy(() => ExerciseResponseSchema),
    "created": z.boolean()
  });
export type ExerciseMutationResponse = z.infer<typeof ExerciseMutationResponseSchema>;

export const ExerciseListResponseSchema = z.object({
    "total": z.number().int(),
    "limit": z.number().int(),
    "offset": z.number().int(),
    "items": z.array(z.lazy(() => ExerciseResponseSchema))
  });
export type ExerciseListResponse = z.infer<typeof ExerciseListResponseSchema>;

export const AssignmentCreateRequestSchema = z.object({
    "activityId": z.string().min(1),
    "activityVersion": z.number().int().min(1),
    "exerciseId": z.string().uuid().optional(),
    "exerciseVersion": z.number().int().min(1).optional(),
    "curriculum": z.lazy(() => CurriculumAnchorSchema),
    "targetSchoolId": z.string().uuid(),
    "targetStudentId": z.string().uuid().optional(),
    "targetClassId": z.string().uuid().optional(),
    "targetGradeLevel": z.string().optional(),
    "targetStageKey": z.string().optional(),
    "source": z.enum(["teacherAssigned", "recommended", "curriculumRequired", "reassessment", "reinforcement"]),
    "dueAt": z.string().optional()
  });
export type AssignmentCreateRequest = z.infer<typeof AssignmentCreateRequestSchema>;

export const AssignmentResponseSchema = z.object({
    "id": z.string().uuid(),
    "tenantId": z.string().uuid(),
    "activityId": z.string(),
    "activityVersion": z.number().int().optional(),
    "exerciseId": z.string().nullable().optional(),
    "curriculumVersion": z.string().optional(),
    "targetSchoolId": z.string(),
    "targetStudentId": z.string().nullable().optional(),
    "targetClassId": z.string().nullable().optional(),
    "assignedBy": z.string().optional(),
    "assignedByRole": z.string().optional(),
    "source": z.string(),
    "status": z.enum(["ACTIVE", "CANCELLED", "CLOSED"]),
    "dueAt": z.string().nullable().optional(),
    "createdAt": z.string().optional()
  });
export type AssignmentResponse = z.infer<typeof AssignmentResponseSchema>;

export const AssignmentMutationResponseSchema = z.object({
    "assignment": z.lazy(() => AssignmentResponseSchema),
    "created": z.boolean()
  });
export type AssignmentMutationResponse = z.infer<typeof AssignmentMutationResponseSchema>;

export const AssignmentListResponseSchema = z.object({
    "total": z.number().int(),
    "limit": z.number().int(),
    "offset": z.number().int(),
    "items": z.array(z.lazy(() => AssignmentResponseSchema))
  });
export type AssignmentListResponse = z.infer<typeof AssignmentListResponseSchema>;

export const AttemptCreateRequestSchema = z.object({
    "activityId": z.string().min(1),
    "assignmentId": z.string().uuid().optional(),
    "exerciseId": z.string().uuid().optional(),
    "curriculum": z.lazy(() => CurriculumAnchorSchema).optional(),
    "attemptNumber": z.number().int().min(1),
    "engineInput": z.record(z.unknown()).optional(),
    "studentId": z.string().uuid().optional()
  });
export type AttemptCreateRequest = z.infer<typeof AttemptCreateRequestSchema>;

export const AttemptResponseSchema = z.object({
    "id": z.string().uuid(),
    "tenantId": z.string().uuid(),
    "studentId": z.string().uuid(),
    "assignmentId": z.string().nullable().optional(),
    "activityId": z.string(),
    "exerciseId": z.string().nullable().optional(),
    "curriculumVersion": z.string().optional(),
    "attemptNumber": z.number().int(),
    "state": z.enum(["CREATED", "STARTED", "IN_PROGRESS", "SUBMITTED", "MEASURED", "EVIDENCE_RECORDED"]),
    "startedAt": z.string().nullable().optional(),
    "submittedAt": z.string().nullable().optional(),
    "durationMs": z.number().int().nullable().optional(),
    "evidenceRef": z.string().nullable().optional(),
    "operationKey": z.string().optional()
  });
export type AttemptResponse = z.infer<typeof AttemptResponseSchema>;

export const AttemptMutationResponseSchema = z.object({
    "attempt": z.lazy(() => AttemptResponseSchema),
    "created": z.boolean()
  });
export type AttemptMutationResponse = z.infer<typeof AttemptMutationResponseSchema>;

export const AttemptListResponseSchema = z.object({
    "total": z.number().int(),
    "limit": z.number().int(),
    "offset": z.number().int(),
    "items": z.array(z.lazy(() => AttemptResponseSchema))
  });
export type AttemptListResponse = z.infer<typeof AttemptListResponseSchema>;

export const AttemptSubmitRequestSchema = z.object({
    "submittedAt": z.string().optional(),
    "durationMs": z.number().int().min(0).optional(),
    "engineInput": z.record(z.unknown()).optional(),
    "time": z.object({
      "activityDurationMs": z.number().int().min(0).optional(),
      "responseDurationMs": z.number().int().min(0).optional(),
      "thinkingDurationMs": z.number().int().min(0).optional(),
      "listeningDurationMs": z.number().int().min(0).optional(),
      "pauseDurationMs": z.number().int().min(0).optional(),
      "replayDurationMs": z.number().int().min(0).optional()
    }).optional()
  });
export type AttemptSubmitRequest = z.infer<typeof AttemptSubmitRequestSchema>;

export const AttemptRecordRequestSchema = z.object({
    "evidenceRef": z.string().uuid()
  });
export type AttemptRecordRequest = z.infer<typeof AttemptRecordRequestSchema>;

export const EvidenceResponseSchema = z.object({
    "id": z.string().uuid(),
    "tenantId": z.string().uuid(),
    "studentId": z.string().uuid(),
    "evidenceType": z.string(),
    "subject": z.string().nullable().optional(),
    "occurredAt": z.string(),
    "sourceEngine": z.string(),
    "activityId": z.string().nullable().optional(),
    "confidence": z.number().nullable().optional(),
    "durationMs": z.number().int().nullable().optional()
  });
export type EvidenceResponse = z.infer<typeof EvidenceResponseSchema>;

export const EvidenceListResponseSchema = z.object({
    "total": z.number().int(),
    "limit": z.number().int(),
    "offset": z.number().int(),
    "items": z.array(z.lazy(() => EvidenceResponseSchema))
  });
export type EvidenceListResponse = z.infer<typeof EvidenceListResponseSchema>;

export const InsightsResponseSchema = z.object({
    "items": z.array(z.object({
      "id": z.string(),
      "signal": z.string(),
      "confidence": z.number(),
      "explanation": z.string(),
      "evidenceRefs": z.array(z.string()).optional(),
      "recommendation": z.record(z.unknown()).nullable().optional()
    }))
  });
export type InsightsResponse = z.infer<typeof InsightsResponseSchema>;

export const AggregateResponseSchema = z.object({
    "groups": z.array(z.object({
      "schoolId": z.string().nullable().optional(),
      "stageKey": z.string().nullable().optional(),
      "gradeLevel": z.string().nullable().optional(),
      "subject": z.string().nullable().optional(),
      "evidenceType": z.string(),
      "mean": z.number().nullable().optional(),
      "sampleSize": z.number().int(),
      "assessedStudents": z.number().int(),
      "studentsInScope": z.number().int(),
      "assessmentCoverage": z.number(),
      "confidence": z.enum(["low", "medium", "high"]),
      "status": z.enum(["OK", "INSUFFICIENT_EVIDENCE"]),
      "trend": z.object({
        "current": z.number().nullable().optional(),
        "previous": z.number().nullable().optional(),
        "direction": z.enum(["UP", "DOWN", "FLAT"]).optional()
      }).nullable().optional(),
      "timePeriod": z.object({
        "from": z.string(),
        "to": z.string()
      })
    }))
  });
export type AggregateResponse = z.infer<typeof AggregateResponseSchema>;
