/**
 * CORE-24 / Wave 3 — Canonical contract GENERATOR (OpenAPI → Zod + Client).
 *
 * THE GOVERNING PRINCIPLE (owner directive): OpenAPI is the source of truth;
 * Zod runtime schemas and the client are GENERATED from lib/api-spec/v1.yaml —
 * never hand-written, never duplicated. Deterministic: two runs produce
 * byte-identical output (contract test pins this).
 *
 * Usage: node lib/api-spec/generate-v1.mjs
 * (yaml resolved from the workspace donor install — no new packages)
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const yaml = require(join(dirname(fileURLToPath(import.meta.url)), "..", "..", "engines", "reading-engine", "node_modules", "js-yaml"));

const specRoot = dirname(fileURLToPath(import.meta.url));
const doc = yaml.load(readFileSync(join(specRoot, "v1.yaml"), "utf8"));

const HTTP_METHODS = new Set(["get", "post", "put", "patch", "delete"]);
const pascal = (s) => s.split(/[^a-zA-Z0-9]+/).filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join("");

// ===== Zod emission (components.schemas → zod) =====

function refName(ref) {
  return pascal(ref.replace("#/components/schemas/", ""));
}

function zodFor(schema, schemas, indent = "  ") {
  if (!schema) return "z.unknown()";
  if (schema.$ref) return `z.lazy(() => ${refName(schema.$ref)}Schema)`;
  let inner;
  if (schema.type === "string") {
    inner = schema.format === "uuid" ? "z.string().uuid()" : schema.format === "email" ? "z.string().email()" : "z.string()";
    if (schema.enum) inner = `z.enum([${schema.enum.map((e) => JSON.stringify(e)).join(", ")}])`;
    if (schema.minLength !== undefined) inner += `.min(${schema.minLength})`;
    if (schema.maxLength !== undefined) inner += `.max(${schema.maxLength})`;
  } else if (schema.type === "integer") {
    inner = "z.number().int()";
    if (schema.minimum !== undefined) inner += `.min(${schema.minimum})`;
    if (schema.maximum !== undefined) inner += `.max(${schema.maximum})`;
  } else if (schema.type === "number") {
    inner = "z.number()";
    if (schema.minimum !== undefined) inner += `.min(${schema.minimum})`;
  } else if (schema.type === "boolean") {
    inner = "z.boolean()";
  } else if (schema.type === "array") {
    inner = `z.array(${zodFor(schema.items, schemas, indent)})`;
  } else if (schema.type === "object") {
    const required = new Set(schema.required ?? []);
    const entries = Object.entries(schema.properties ?? {}).map(([k, v]) => {
      const z = zodFor(v, schemas, indent + "  ");
      return `${indent}  ${JSON.stringify(k)}: ${required.has(k) ? z : z + ".optional()"}`;
    });
    inner = `z.object({\n${entries.join(",\n")}\n${indent}})`;
    if (schema.additionalProperties === true && !schema.properties) inner = "z.record(z.unknown())";
  } else {
    inner = "z.unknown()";
  }
  if (schema.nullable) inner += ".nullable()";
  return inner;
}

function emitZod() {
  const schemas = doc.components?.schemas ?? {};
  const blocks = [];
  for (const [name, schema] of Object.entries(schemas)) {
    const z = zodFor(schema, schemas);
    // inferred TS type rides along — the client and routers import these types
    blocks.push(`export const ${pascal(name)}Schema = ${z};\nexport type ${pascal(name)} = z.infer<typeof ${pascal(name)}Schema>;`);
  }
  const header = `/**
 * GENERATED by lib/api-spec/generate-v1.mjs from lib/api-spec/v1.yaml — DO NOT EDIT.
 * Source of truth: the OpenAPI contract (CORE-24 Wave 3 governing principle).
 * Zod runtime validation mirrors (used by /v1 routers for body/query/params).
 */
import { z } from "zod";
`;
  writeFileSync(join(specRoot, "..", "api-zod", "src", "v1-schemas.generated.ts"), header + "\n" + blocks.join("\n\n") + "\n");
  return Object.keys(schemas).length;
}

// ===== Client emission (paths → typed endpoint descriptors + fetch invoker) =====

function refToType(ref) {
  return ref ? pascal(ref.replace("#/components/schemas/", "")) : null;
}

function emitClient() {
  const lines = [];
  const endpoints = [];
  const usedSchemaTypes = new Set();
  const compParams = doc.components?.parameters ?? {};
  const resolveParam = (p) => (p.$ref ? compParams[p.$ref.replace("#/components/parameters/", "")] ?? {} : p);
  for (const [path, pathItem] of Object.entries(doc.paths)) {
    for (const [method, op] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method)) continue;
      const operationId = op.operationId;
      const reqRef = refToType(op.requestBody?.content?.["application/json"]?.schema?.$ref);
      const okRef = refToType(op.responses?.["200"]?.content?.["application/json"]?.schema?.$ref ?? op.responses?.["201"]?.content?.["application/json"]?.schema?.$ref);
      if (reqRef) usedSchemaTypes.add(reqRef);
      if (okRef) usedSchemaTypes.add(okRef);
      const paramNames = [...path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
      // Resolve parameter $refs against components.parameters (contract-faithful).
      const params = (op.parameters ?? []).map(resolveParam);
      const queryNames = params.filter((p) => p.in === "query").map((p) => p.name);
      const headerNames = params.filter((p) => p.in === "header").map((p) => p.name);
      const reqType = reqRef ?? (["post", "put", "patch"].includes(method) && (op.requestBody?.required || Object.keys(op.requestBody?.content ?? {}).length) ? "Record<string, unknown>" : null);
      const resType = okRef ?? "unknown";
      lines.push(`export const ${operationId}Endpoint = {`);
      lines.push(`  operationId: ${JSON.stringify(operationId)},`);
      lines.push(`  method: ${JSON.stringify(method.toUpperCase())},`);
      lines.push(`  path: ${JSON.stringify(path)},`);
      lines.push(`  params: [${paramNames.map((p) => JSON.stringify(p)).join(", ")}],`);
      lines.push(`  query: [${queryNames.map((p) => JSON.stringify(p)).join(", ")}],`);
      lines.push(`  headers: [${headerNames.map((p) => JSON.stringify(p)).join(", ")}],`);
      lines.push(`  idempotent: ${JSON.stringify(method === "get")},`);
      lines.push(`} as const;`);
      // Op-level aliases are NAMESPACED (…ApiRequest/…ApiResponse) so they can
      // never collide with (or circularly alias) the shared schema type names.
      lines.push(`export type ${pascal(operationId)}ApiRequest = ${reqType ?? "undefined"};`);
      lines.push(`export type ${pascal(operationId)}ApiResponse = ${resType};`);
      lines.push("");
      endpoints.push(operationId);
    }
  }
  const runtime = `

/** Single canonical invoker (apps/web uses the generated types + custom fetch). */
export async function callV1<O extends { operationId: string; method: string; path: string; params: string[]; query: string[]; headers: string[] }>(
  endpoint: O,
  args: {
    params?: Record<string, string>;
    query?: Record<string, string | number | undefined>;
    body?: unknown;
    headers?: Record<string, string>;
  } = {},
  http: { baseUrl: string; token?: string; fetchImpl?: typeof fetch } = { baseUrl: "/v1" },
): Promise<Response> {
  const f = http.fetchImpl ?? fetch;
  let url = http.baseUrl + endpoint.path;
  for (const p of endpoint.params) url = url.replace("{" + p + "}", encodeURIComponent(args.params?.[p] ?? ""));
  const qs = endpoint.query
    .filter((q) => args.query?.[q] !== undefined && args.query?.[q] !== "")
    .map((q) => encodeURIComponent(q) + "=" + encodeURIComponent(String(args.query![q]!)))
    .join("&");
  if (qs) url += "?" + qs;
  return f(url, {
    method: endpoint.method,
    headers: {
      ...(args.body !== undefined ? { "content-type": "application/json" } : {}),
      ...(http.token ? { authorization: "Bearer " + http.token } : {}),
      ...Object.fromEntries(endpoint.headers.filter((h) => args.headers?.[h] !== undefined).map((h) => [h, args.headers![h]!])),
      ...args.headers,
    },
    ...(args.body !== undefined ? { body: JSON.stringify(args.body) } : {}),
  });
}
`;
  const header = `/**
 * GENERATED by lib/api-spec/generate-v1.mjs from lib/api-spec/v1.yaml — DO NOT EDIT.
 * Canonical /v1 client surface (CORE-24 Wave 3): endpoint descriptors + inferred
 * request/response types + one invoker. apps/web consumes these — no duplication.
 * Schema types are IMPORTED from @workspace/api-zod (OpenAPI is the single source).
 */

/* eslint-disable */

${usedSchemaTypes.size ? `import type { ${[...usedSchemaTypes].sort().join(", ")} } from "@workspace/api-zod";\n` : ""}`;
  writeFileSync(join(specRoot, "..", "api-client-react", "src", "generated", "v1-client.generated.ts"), header + lines.join("\n") + runtime);
  return endpoints.length;
}

mkdirSync(join(specRoot, "..", "api-zod", "src"), { recursive: true });
mkdirSync(join(specRoot, "..", "api-client-react", "src", "generated"), { recursive: true });
const schemaCount = emitZod();
const endpointCount = emitClient();
console.log(`[generate-v1] zod schemas: ${schemaCount} → lib/api-zod/src/v1-schemas.generated.ts`);
console.log(`[generate-v1] client endpoints: ${endpointCount} → lib/api-client-react/src/generated/v1-client.generated.ts`);
