import { injectable } from "inversify";
import catalog from "./catalog.json" with { type: "json" };
import type { Exercise } from "@buytuk/contracts";

/**
 * Exercise Library
 *
 * Curated, pedagogically-reviewed exercises.
 * NOT generated by LLM — LLM only reformulates instructions.
 */
@injectable()
export class ExerciseLibrary {
  private catalog = catalog;

  findByFocus(phonemes: string[]): Exercise[] {
    const all = this.getAllExercises();
    return all.filter(ex =>
      (ex as any).focus.includes("all") ||
      (ex as any).focus.some((f: string) => phonemes.includes(f))
    );
  }

  getById(id: string): Exercise | undefined {
    const all = this.getAllExercises();
    return all.find(e => e.id === id);
  }

  getByType(type: Exercise["type"]): Exercise[] {
    return (this.catalog as any)[type] || [];
  }

  getByDifficulty(difficulty: number): Exercise[] {
    const all = this.getAllExercises();
    return all.filter(e => e.difficulty === difficulty);
  }

  getAllExercises(): Exercise[] {
    return [
      ...this.catalog.minimal_pairs,
      ...this.catalog.tongue_twisters,
      ...this.catalog.syllable_drills,
      ...this.catalog.contextual_reading,
    ] as unknown as Exercise[];
  }

  search(keyword: string): Exercise[] {
    const all = this.getAllExercises();
    const lower = keyword.toLowerCase();
    return all.filter(e =>
      e.title.toLowerCase().includes(lower) ||
      e.instructions.toLowerCase().includes(lower)
    );
  }
}
